// components/app/download.tsx
import React from "react";

export default function AppDownload({ title, version, desc, id, children }: { title: string; version: string; desc: string; id: string; children: React.ReactNode }) {
  return (
    <div className="flex-1 bg-white border border-gray-200 rounded-2xl shadow-md min-w-[260px] max-w-md p-5 flex flex-col justify-between" id={id}>
      <div>
        <div className="flex items-center gap-2 mb-2">
          <h2 className="text-xl font-bold text-black">{title}</h2>
          <span className="inline-block bg-red-200 text-black text-xs font-semibold px-2 py-0.5 rounded">{version}</span>
        </div>
        <p className="mb-3 text-black text-base">{desc}</p>
      </div>
      <div className="flex gap-2 items-end content-center mt-2">{children}</div>
    </div>
  );
}

// components/app/download.vue
<script setup lang="ts">
interface Props {
  title: string,
  desc: string,
  version: string,
  id: string,
}

const props = defineProps<Props>();
</script>

<template>
  <div class="flex-1 card bg-white border rounded-2xl shadow-xl" :id="props.id" style="min-width: 400px;">
    <div class="card-body">
      <h2 class="card-title">{{ title }}<div class="badge badge-primary">{{ version }}</div>
      </h2>
      <p> {{ desc }} </p>

      <div class="card-actions justify-end">
        <slot></slot>
      </div>
    </div>
  </div></template>
