// components/app/feature.tsx
import React from "react";

export default function AppFeature({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="p-5 bg-white border border-gray-200 rounded-2xl shadow-md flex-1 grow min-w-[260px]">
      <h3 className="text-2xl font-bold text-black mb-2">{title}</h3>
      <div className="text-black text-base">{children}</div>
    </div>
  );
}

// components/app/feature.vue
<script setup lang="ts">
interface Props {
  title: string,
}

const props = defineProps<Props>();
</script>

<template>
  <div class="p-5 bg-white border rounded-2xl shadow-xl lg:flex-1 grow">
    <div class="flex flex-col">
      <h2 class="text-2xl font-bold text-black">{{ props.title }}</h2>
      <slot></slot>
    </div>
  </div>
</template>
